languageCode = "en-us"
title = "DigitalRooster"
baseurl = "https://www.digitalrooster.dev/"
theme = "forty"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Thomas Ruschival"
  description = "Your hackable alarm clock, podcast player and internet radio"

  # Link custom assets relative to /static
  custom_css = ["custom.css"]
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [DigitalRooster](http://digitalrooster.dev/)"

  # Navigation Section
  [params.navigation]
    title = "DigitalRooster"
    subtitle = "Navigate"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "digital_rooster_low_poly.svg"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Contribuiting"
      url = "pages/contributing"

    [[params.navigation.links]]
      name = "Hardware"
      url = "pages/hardware"

    [[params.navigation.links]]
      name = "Software"
      url = "pages/software"

    [[params.navigation.links]]
      name = "Safety Instructions"
      url = "pages/safety"

    [[params.navigation.links]]
      name = "About this Website"
      url = "pages/about"

    [[params.navigation.links]]
      name = "Privacy and Data Protection"
      url = "pages/privacy"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
     # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # # Button Style 1
    # [[params.navigation.button1]]
    #   name = "Get Started"
    #   url = "blogs"

    # # Button Style 2
    # [[params.navigation.button2]]
    #   name = "Log In"
    #   url = "#"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome to DigitalRooster"
    subtitle = "Your hackable alarm clock, internet radio, podcast player or whatever else you want it to be!"
    buttonText = "Get Started"

  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    [[params.tiles.showcase]]
      title = "Overview"
      subtitle = "Why, What and How"
      image = "satellite_img.webp"
      url = "pages/main"

    [[params.tiles.showcase]]
      title = "Software"
      subtitle = "What's inside"
      image = "coding_small.webp"
      url = "pages/software"

    [[params.tiles.showcase]]
      title = "Hardware"
      subtitle = "The tangible DigitalRooster"
      image = "hardware_pcb.webp"
      url = "pages/hardware"

    [[params.tiles.showcase]]
      title = "Contributing"
      subtitle = "How to contribute"
      image = "contributing.webp"
      url = "pages/contributing"

  # Section Type Two
  # [params.two]
  #   enable = true
  #   title = "News"
  #   subtitle = """Project updates"""
  #   buttonText = "read more"
  #   url = "/news/"

  # Section Type news - shortened project news
  [params.news]
    enable = true
    title = "Project Updates"
    buttonText = "read all updates"
	url = "/news/"

  # Contact section
  [params.contact]
    enable = false
    form = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "t.ruschival@gmail.com"

    # [[params.contact.phone]]
    # title = "Phone"
    # phone = "(000) 000-0000 x1234"

    # [[params.contact.address]]
    # title = "Address"
    # street = "Street"
    # city = "City, ST 00000"
    # country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "2019 - Thomas Ruschival"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/truschival/"
      label = "GitHub"

    [[params.footer.quicklinks]]
      #text = "Web Design"
      url= "https://github.com/MarcusVirg/forty"
      alt = "Theme 'forty' for hugo designed by Marcus Virginia"

    [[params.footer.quicklinks]]
      #text = "Privacy"
      url= "/pages/privacy"
      alt = "Privacy and data protection"

# New goldmark render settings for Hugo > 0.6
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

